name: getx_confetti
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  confetti: ^0.8.0
  flutter:
    sdk: flutter
#  flutter_confetti: ^0.3.4
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

get_cli:
    sub_folder: false   
